"""Manual source file assets (one uploaded sheet = one Parquet file).

An asset is created *staged* (``datasource_id`` NULL, ``expires_at`` set) by
``POST /datasources/manual/parse-file`` and *bound* to a manual DataSource when
that source is created/updated with a config referencing the asset id. Bound
assets never expire; they are removed with their source (FK ON DELETE CASCADE
for the row, a session hook for the file).

``storage_key`` is generated by the server and never taken from a request.
"""
import uuid

from sqlalchemy import Column, DateTime, ForeignKey, Integer, JSON, String, BigInteger
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func

from app.core.database import Base


class ManualSourceAsset(Base):
    __tablename__ = "manual_source_assets"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    datasource_id = Column(
        Integer, ForeignKey("data_sources.id", ondelete="CASCADE"), nullable=True, index=True,
    )
    owner_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    sheet_name = Column(String(255), nullable=False)
    storage_key = Column(String(255), nullable=False, unique=True)
    original_filename = Column(String(255), nullable=True)
    media_type = Column(String(100), nullable=True)
    size_bytes = Column(BigInteger, nullable=False, default=0)
    sha256 = Column(String(64), nullable=False)
    columns = Column(JSON, nullable=False, default=list)
    row_count = Column(Integer, nullable=False, default=0)
    revision = Column(Integer, nullable=False, default=1)
    expires_at = Column(DateTime(timezone=True), nullable=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False,
    )
