"""Storage abstraction for manual-source file assets.

Keys are generated by the server (``new_storage_key``) and validated on every
access, so a key can never address anything outside the storage root.
"""
from __future__ import annotations

import os
import pathlib
import re
import uuid
from typing import Optional, Protocol

_KEY_RE = re.compile(r"^[0-9a-f]{32}\.parquet$")


class InvalidStorageKey(ValueError):
    pass


def new_storage_key() -> str:
    return f"{uuid.uuid4().hex}.parquet"


def validate_storage_key(key: str) -> str:
    if not isinstance(key, str) or not _KEY_RE.match(key):
        raise InvalidStorageKey("invalid storage key")
    return key


class AssetStorage(Protocol):
    def write_bytes(self, key: str, data: bytes) -> None: ...
    def path_for(self, key: str) -> pathlib.Path: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...


class LocalFileStorage:
    """Files under ``<root>/<key[:2]>/<key>``; atomic write via tmp + rename."""

    def __init__(self, root: pathlib.Path):
        self.root = pathlib.Path(root).resolve()

    def path_for(self, key: str) -> pathlib.Path:
        validate_storage_key(key)
        path = (self.root / key[:2] / key).resolve()
        if self.root not in path.parents:
            raise InvalidStorageKey("invalid storage key")
        return path

    def write_bytes(self, key: str, data: bytes) -> None:
        path = self.path_for(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
        try:
            with open(tmp, "wb") as fh:
                fh.write(data)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp, path)
        finally:
            if tmp.exists():
                tmp.unlink()

    def exists(self, key: str) -> bool:
        return self.path_for(key).is_file()

    def delete(self, key: str) -> None:
        try:
            self.path_for(key).unlink()
        except FileNotFoundError:
            pass


_storage_override: Optional[AssetStorage] = None


def get_storage() -> AssetStorage:
    if _storage_override is not None:
        return _storage_override
    from app.core.config import settings

    return LocalFileStorage(settings.data_dir_path / "manual_assets")


def set_storage_override(storage: Optional[AssetStorage]) -> None:
    """Tests only."""
    global _storage_override
    _storage_override = storage
