"""Add Google Sheets and Manual datasource types

Revision ID: 663a8a9779ce
Revises: 6e9cb7ed72f6
Create Date: 2025-12-25 17:27:39.048070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '663a8a9779ce'
down_revision = '6e9cb7ed72f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dashboard_filters_id', table_name='dashboard_filters')
    op.drop_table('dashboard_filters')
    op.alter_column('dataset_workspace_tables', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dataset_workspace_tables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_dataset_workspace_tables_datasource_id'), 'dataset_workspace_tables', ['datasource_id'], unique=False)
    op.create_index(op.f('ix_dataset_workspace_tables_workspace_id'), 'dataset_workspace_tables', ['workspace_id'], unique=False)
    op.alter_column('dataset_workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dataset_workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_workspaces', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dataset_workspaces', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_dataset_workspace_tables_workspace_id'), table_name='dataset_workspace_tables')
    op.drop_index(op.f('ix_dataset_workspace_tables_datasource_id'), table_name='dataset_workspace_tables')
    op.alter_column('dataset_workspace_tables', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dataset_workspace_tables', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('dashboard_filters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operator', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name='dashboard_filters_dashboard_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dashboard_filters_pkey')
    )
    op.create_index('ix_dashboard_filters_id', 'dashboard_filters', ['id'], unique=False)
    # ### end Alembic commands ###
