"""Initial migration

Revision ID: d282b9fbb143
Revises: 8d2143719709
Create Date: 2025-12-01 10:15:20.402721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd282b9fbb143'
down_revision = '8d2143719709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
