"""Add semantic layer tables

Revision ID: 2dcecd094e39
Revises: d282b9fbb143
Create Date: 2025-12-06 09:27:05.733780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcecd094e39'
down_revision = 'd282b9fbb143'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_models_id'), 'semantic_models', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_models_name'), 'semantic_models', ['name'], unique=True)
    op.create_table('semantic_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sql_table_name', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('measures', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_views_id'), 'semantic_views', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_views_name'), 'semantic_views', ['name'], unique=True)
    op.create_table('semantic_explores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('base_view_id', sa.Integer(), nullable=False),
    sa.Column('base_view_name', sa.String(), nullable=False),
    sa.Column('joins', sa.JSON(), nullable=False),
    sa.Column('default_filters', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_view_id'], ['semantic_views.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['semantic_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_explores_id'), 'semantic_explores', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_explores_name'), 'semantic_explores', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_explores_name'), table_name='semantic_explores')
    op.drop_index(op.f('ix_semantic_explores_id'), table_name='semantic_explores')
    op.drop_table('semantic_explores')
    op.drop_index(op.f('ix_semantic_views_name'), table_name='semantic_views')
    op.drop_index(op.f('ix_semantic_views_id'), table_name='semantic_views')
    op.drop_table('semantic_views')
    op.drop_index(op.f('ix_semantic_models_name'), table_name='semantic_models')
    op.drop_index(op.f('ix_semantic_models_id'), table_name='semantic_models')
    op.drop_table('semantic_models')
    # ### end Alembic commands ###
