"""add_type_overrides_to_workspace_tables

Revision ID: a064bf26d7e1
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 16:23:24.861489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a064bf26d7e1'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_workspace_tables', sa.Column('type_overrides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_workspace_tables', 'type_overrides')
    # ### end Alembic commands ###
